# https://tomasvotruba.com/blog/2020/11/16/how-to-make-dynamic-matrix-in-github-actions/
name: "Abstract v4(secrets)"
# TODO: major rework: use inputs. from release-config.json instead of selected JSON properties --> more dynamic and adaptable
on:
  workflow_call:
    inputs:
      stage:
        required: false
        type: string
        description: 'Stage'
      namespace:
        required: false
        type: string
        description: 'ns1'
      secrets_map:
        required: false
        type: string
        description: '{"ns1":["secretA"],"ns2":["secretA","secretB"]}'
jobs:
  k8s-secrets:
    runs-on: ubuntu-20.04
    name: "K8s-Namespace-Secrets"
    env: 
      SECRET_NAME: "DEV_PROVIDER_USERNAME"
    steps:
      - shell: bash
        run: |

          export namespace="${{inputs.namespace}}"
          echo "[DEBUG] namespace=${namespace}"
          secrets_map=${{toJSON(inputs.secrets_map)}}
          k8s_secrets=$(echo ${secrets_map} | jq -r -c '.[env.namespace].k8s_secrets')
          echo "[DEBUG] k8s_secrets=${k8s_secrets}"

          # TODO: POC/EVAL if i can pass secrets env.SECRET_NAME to TF-Apply to stop sink time in hopeless feature...
          # TODO: replace <STAGE> (# IMPROVE: /# FEATURE: and <NAMESPACE>)
          # TODO: get value from secret for every secret --> action?

          # TODO: Collect results --> files? Map? ~> TF reports? 
          # TODO: Join to one map
          # TODO: pass Secret/NS-Map to TF-Job in Layer-2